version: 2

jobs:
  buildDev:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: ./gradlew assemble
      - run: ./gradlew build
      - run: ./gradlew test
      - store_artifacts:
          path: target
          destination: build

workflows:
  version: 2
  build:
    jobs:
      - buildDev
